sudo: false
language: node_js
node_js: 10
cache: yarn
jobs:
  include:
    - stage: test
      env:
        - TARGET="node"
      script: npm run test:node
    - stage: test-shim
      env:
        - TARGET="webpack"
      script: npm run test:webpack
    - stage: test-shim
      env:
        - TARGET="browserify"
      script: npm run test:browserify
  fast_finish: true
  allow_failures:
    - env:
      - TARGET="webpack" TARGET="browserify"
