sudo: false
language: node_js
node_js: 8
cache: yarn
jobs:
  include:
    - stage: test
      env:
        - TARGET_1="node"
      script: npm run test:node
    - stage: test
      env:
        - TARGET_2="webpack"
      script: npm run test:webpack
    - stage: test
      env:
        - TARGET_3="browserify"
      script: npm run test:browserify
  fast_finish: true
  allow_failures:
    - env:
      - TARGET_2="webpack" TARGET_3="browserify"